name: CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: "9.x"
  USERNAME: Liveron

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Authenticate GitHub
      run: |  
       dotnet nuget add source https://nuget.pkg.github.com/Liveron/index.json \
       --username ${{ env.USERNAME }} --password ${{ secrets.NUGET_PACKAGES_ACCESS_TOKEN }} \
       --store-password-in-clear-text --name github
        
    
    - name: Restore dependencies         
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build  