name: CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: "9.x"
  USERNAME: Liveron

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies         
      run: dotnet restore

<<<<<<< HEAD
    - name: Build
      run: dotnet build --configuration Release --no-restore
=======
    - name: Show ls
      run: |
        ls
        pwd

    - name: Build and publish
      run: dotnet publish --configuration Release --no-restore --output ./publish
>>>>>>> 913f3874e19f8d1648c813aca6118e76cc99d4a9

    - name: Test
      run: dotnet test --no-build  